### ISSUE TITLE
Addition of yml file is not triggering any PR creation even though orbs are out of date

### ISSUE THREAD

**Issue by darren-arbon** [BESTSELLER/dependabot-circleci#119]
I have added this yml file
```
labels:
  - dependencies
  - circleci
target-branch: Upgrade-Otis-circle-orbs
```
and I know all of my circle orbs need updating, but no PRs are being created. Please help!

**Comment by brondum** [comment]
Hi @darrenarbontalis it is our readme that is missing some steps. I will get back to you when we have updated it :)

**Comment by brondum** [comment]
Sorry for the delay @darrenarbontalis, we will get there in the new year :)

**Comment by darrenarbontalis** [comment]
@brondum no probs, I manually upgraded them for now.

**Comment by Gaardsholt** [comment]
We finally had the time to finish this!
It is now ready to use and available to be installed from https://github.com/apps/dependabot-circleci

Please let us know if you have any issues with it :)
